settings:
  use_local: 0

  landmarks_to_pick:
    - "left_shoulder"
    - "right_shoulder"
    - "left_hip"
    - "right_hip"
    - "left_knee"
    - "right_knee"
    - "left_ankle"
    - "right_ankle"
    - "left_foot_index"
    - "right_foot_index"
  testing: False
  normalize_landmarks: False
  model_name: "KNN_model"
  
  tf_lite_model: "lightning_int8.tflite"
#    - 'thunder.tflite' #  256# flaot
#    - 'thunder_int8.tflite' # 256 UINT8 #SLOW
#    - 'lightning_int8.tflite' # 192 UINT8 #SLOW
#    - 'lightning_float16.tflite'#  192 # moet nog naar uint8
#    - 'thunder_float16.tflite' # 256 # moet nog naar uint8
#    - 'lightning.tflite' # 192 # snel float


