settings:
  amount: -1
  landmarks_to_pick:
    - left_shoulder
    - right_shoulder
    - left_hip
    - right_hip
    - left_knee
    - right_knee
    - left_ankle
    - right_ankle
    - left_foot_index
    - right_foot_index
  tf_lite_model: thunder_float16.tflite
  color: false
  trainmode: false