settings:
  amount: -1
  baseline_model: None
  landmarks_to_pick:
    - left_shoulder
    - right_shoulder
    - left_hip
    - right_hip
    - left_knee
    - right_knee
    - left_ankle
    - right_ankle
    - left_foot_index
    - right_foot_index
  normalize_landmarks: true
  testing: false
  tf_lite_model: thunder_float16.tflite
  use_local: 0
  color: false
