settings:
  amount: 11
  baseline_model: SVC
  flat_array: true
  landmarks_to_pick:
  - left_shoulder
  - right_shoulder
  - left_hip
  - right_hip
  - left_knee
  - right_knee
  - left_ankle
  - right_ankle
  - left_foot_index
  - right_foot_index
  model_name: KNN_model
  normalize_landmarks: false
  testing: false
  tf_lite_model: thunder_float16.tflite
  use_local: 0
